[tool.poetry]
name = "sortiro"
version = "1.0.1"
description = ""
authors = ["artemdorozhkin"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
aiogram = "^3.12.0"
python-dotenv = "^1.0.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
